'use client';
import { useEffect, useMemo, useState } from 'react';
import { accounts, events, markets, positions, strategies } from '@/data/mock/repository';
import { mockTerminalProvider } from '@/data/mock/mock-terminal-provider';

const nav=[['CMD','Command Center'],['STR','Strategies'],['PF','Portfolio'],['PROP','Prop Firms'],['RSK','Risk'],['MKT','Markets'],['MAC','Macro'],['JRN','Journal'],['RES','Research'],['SYS','System']];
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const Badge=({children,tone='neutral'}:{children:React.ReactNode,tone?:string})=><span className={`badge ${tone}`}>{children}</span>;
const Panel=({title,meta,children,className=''}:{title:string;meta?:string;children:React.ReactNode;className?:string})=><section className={`panel ${className}`}><header className="panel-head"><b>{title}</b>{meta&&<span>{meta}</span>}</header>{children}</section>;
const Table=({heads,rows}:{heads:string[];rows:(React.ReactNode[])[]})=><div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>;
const Meter=({label,value,limit=100,tone='blue'}:{label:string;value:number;limit?:number;tone?:string})=><div className="meter"><div><span>{label}</span><b>{value}{limit===100?'%':''}</b></div><i><em className={tone} style={{width:`${Math.min(value/limit*100,100)}%`}}/></i></div>;

function CommandCenter(){return <div className="workspace-grid">
 <div className="metric-strip full">{[['COMBINED EQUITY','$102,960'],['SESSION P&L','+$418'],['WEEK','+$1,284'],['REALIZED','+$255'],['UNREALIZED','+$613'],['OPEN RISK','$364'],['RISK USE','46%'],['POSITIONS','2']].map((m,i)=><div key={m[0]}><small>{m[0]}</small><strong className={i===6?'warn':i>0&&i<5?'up':''}>{m[1]}</strong></div>)}</div>
 <Panel title="STRATEGY MONITOR" meta="4 REGISTERED" className="span8"><Table heads={['STRATEGY','MKT','LIFECYCLE','MODE','SIGNAL','POSITION','DAY R','ROLLING R','HEALTH']} rows={strategies.map(s=>[s.name,s.market,<Badge tone="blue">{s.lifecycle}</Badge>,s.mode,s.signal,s.position,s.dailyR===null?'—':`${s.dailyR>=0?'+':''}${s.dailyR.toFixed(2)}`,s.rollingR===null?'—':`+${s.rollingR.toFixed(2)}`,<Badge tone={s.health==='HEALTHY'?'green':s.health==='VALIDATING'?'amber':'neutral'}>{s.health}</Badge>])}/></Panel>
 <Panel title="RISK MONITOR" meta="NORMAL" className="span4 risk"><Meter label="Portfolio utilization" value={46}/><Meter label="Correlated exposure" value={62} tone="amber"/><Meter label="Instrument concentration" value={41}/><Meter label="Daily loss utilization" value={18}/><Meter label="Account drawdown" value={31}/><div className="risk-foot"><span>Current heat <b>0.46%</b></span><span>Max heat <b>1.00%</b></span></div></Panel>
 <Panel title="OPEN POSITIONS" meta="$364 WORST-CASE RISK" className="span8"><Table heads={['SYMBOL','SIDE','QTY','ENTRY','LAST','STOP','UNREAL.','RISK','STRATEGY','ACCOUNT']} rows={positions.map(p=>[<b>{p.symbol}</b>,<span className="up">{p.side}</span>,p.qty,p.entry.toLocaleString(),p.last.toLocaleString(),p.stop.toLocaleString(),<span className="up">+{money(p.pnl)}</span>,money(p.risk),p.strategy,p.account])}/></Panel>
 <Panel title="NEXT HIGH IMPACT EVENT" meta="LOCKOUT SOON" className="span4 event"><div className="event-main"><div><small>US · HIGH IMPACT</small><strong>FOMC Minutes</strong><span>14:00 ET · Today</span></div><div className="count">00:27:38<small>REMAINING</small></div></div><div className="lock"><Badge tone="amber">LOCKOUT SOON</Badge><span>New entries disabled from 13:55–14:10 ET</span></div></Panel>
 <Panel title="ACCOUNT HEALTH" meta="2 ACTIVE" className="span7"><Table heads={['ACCOUNT','FIRM / PRODUCT','STAGE','EQUITY','DD REMAINING','BUFFER','STATUS']} rows={accounts.map(a=>[<b>{a.id}</b>,<span>{a.firm}<small className="sub">{a.product}</small></span>,a.stage,money(a.equity),money(a.drawdownRemaining),money(a.buffer),<Badge tone="green">{a.status}</Badge>])}/></Panel>
 <Panel title="SYSTEM EVENT STREAM" meta="LIVE · JOURNAL:EVENT" className="span5"><div className="stream">{events.map(e=><div key={e.time}><time>{e.time}</time><Badge tone={e.severity==='warning'?'amber':'neutral'}>{e.type}</Badge><span>{e.description}</span></div>)}</div></Panel>
 <Panel title="SYSTEM STATUS" meta="HEARTBEAT 328 ms" className="span7"><div className="system-strip">{[['AITRADER CORE','HEALTHY'],['RISK ENGINE','HEALTHY'],['PROP ENGINE','HEALTHY'],['MARKET DATA','MOCK'],['EXECUTION','PAPER'],['JOURNAL','HEALTHY']].map(service=><span key={service[0]}><small>{service[0]}</small><b className={service[1]==='HEALTHY'?'up':''}>{service[1]}</b></span>)}</div></Panel>
 <Panel title="ASK AITRADER" meta="READ-ONLY · ARCHITECTURE PREVIEW" className="span5"><div className="ask"><span>Explain current state using AITRADER data.</span><button>Why did NQ not trade?</button><small>Retrieval only. No signals, parameters, or controls.</small></div></Panel>
 </div>}

function Workspace({code}:{code:string}){
 if(code==='STR') return <><Title title="Strategy Registry" sub="Lifecycle, allocation, validation and execution governance"/><Panel title="ALL STRATEGIES" meta="SELECT ROW FOR DETAIL"><Table heads={['STRATEGY','INSTRUMENT','FAMILY','LIFECYCLE','MODE','TRADES','WIN RATE','EXPECTANCY','PROFIT FACTOR','ALLOCATION','HASH']} rows={strategies.map(s=>[<b>{s.name}</b>,s.market,s.family,<Badge tone="blue">{s.lifecycle}</Badge>,s.mode,s.trades,`${s.winRate}%`,`${s.expectancy.toFixed(2)}R`,s.profitFactor,`${s.allocation}%`,<code>{s.hash}</code>])}/></Panel><div className="two"><Panel title="GC VWAP V2 · VALIDATION" meta="PHASE 26"><div className="facts">{[['Frozen status','VERIFIED'],['In sample','PASS'],['Holdout','PASS'],['Cost overlay','PASS'],['Forward test','ACTIVE'],['Config changes','NONE']].map(x=><span><small>{x[0]}</small><b>{x[1]}</b></span>)}</div></Panel><Panel title="RESEARCH LINEAGE" meta="IMMUTABLE"><div className="lineage">PHASE 23 <i/> PHASE 24 <i/> PHASE 26 <i/> <b>FROZEN</b></div><p className="muted">Hash a71f9c2 verified · no configuration drift detected.</p></Panel></div></>;
 if(code==='PROP') return <><Title title="Prop Firm Operations" sub="Operational capital, compliance limits and payout readiness"/><Panel title="ACCOUNT REGISTRY" meta="2 ACTIVE"><Table heads={['ACCOUNT','FIRM','PRODUCT','STAGE','SIZE','EQUITY','PROFIT','DD TYPE','DD REMAINING','PAYOUT BUFFER','CONSISTENCY','DAYS','STATUS']} rows={accounts.map(a=>[<b>{a.id}</b>,a.firm,a.product,a.stage,money(a.size),money(a.equity),money(a.equity-a.size),'EOD',money(a.drawdownRemaining),money(a.buffer),`${a.consistency}%`,a.tradingDays,<Badge tone="green">SAFE</Badge>])}/></Panel><div className="two"><Panel title="MFFU-01 · RULE ENGINE" meta="LAST CHECK 14:31:44"><Table heads={['RULE','CURRENT','LIMIT','STATUS']} rows={[["EOD Max Loss","$310 used","$2,000",<Badge tone="green">SAFE</Badge>],["Contracts","2 minis","3",<Badge tone="green">SAFE</Badge>],["Consistency","24%","30%",<Badge tone="green">SAFE</Badge>],["Trading Days","8","5",<Badge tone="green">COMPLETE</Badge>],["News","None","Restricted",<Badge tone="green">SAFE</Badge>]]}/></Panel><Panel title="PAYOUT READINESS" meta="MFFU-01"><div className="readiness"><Badge tone="amber">NOT YET ELIGIBLE</Badge><strong>2 days</strong><span>until next payout window</span><hr/><div><span>Profit buffer</span><b>$2,040</b></div><div><span>Rule blockers</span><b>Minimum cycle days</b></div><div><span>Window opens</span><b>22 Aug 2026</b></div></div></Panel></div></>;
 if(code==='RSK') return <><Title title="Risk Control" sub="Portfolio heat, account loss allowance and correlated exposure"/><div className="metric-strip">{[['SAFETY STATE','NORMAL'],['CURRENT HEAT','0.46%'],['MAX HEAT','1.00%'],['OPEN R','0.74R'],['DAILY TOTAL','+0.42R'],['WEEKLY','+1.84R']].map(m=><div><small>{m[0]}</small><strong>{m[1]}</strong></div>)}</div><div className="two"><Panel title="CORRELATED RISK" meta="1 ACTIVE CLUSTER"><div className="cluster"><Badge tone="amber">US EQUITY INDEX</Badge><strong>NQ LONG + ES LONG</strong><span>Combined risk <b>0.62%</b></span><p>Two positions express one correlated portfolio exposure. Entry capacity reduced by 38%.</p></div></Panel><Panel title="ACCOUNT LOSS ALLOWANCE"><Table heads={['ACCOUNT','DD REMAINING','EXPOSURE','WORST CASE','UTILIZATION']} rows={accounts.map((a,i)=>[a.id,money(a.drawdownRemaining),i?'$200':'$164',i?'$248':'$202',`${i?22:31}%`])}/></Panel></div><Panel title="SAFETY POLICY STATE"><div className="safe-state"><b>NORMAL</b><span>All risk engines are within configured thresholds. New entries permitted subject to news and correlation policy.</span></div></Panel></>;
 if(code==='MKT') return <><Title title="Markets" sub="Contextual monitoring · strategy logic remains in AITRADER Core"/><Panel title="PRIMARY FUTURES" meta="MOCK FEED · 126ms"><Table heads={['SYMBOL','CONTRACT','LAST','SESSION','HIGH','LOW','VWAP','ATR','STRATEGY STATE','SIGNAL','NEXT EVENT']} rows={markets.map(m=>[<b>{m.symbol}</b>,m.name,m.price,<span className={m.change[0]==='+'?'up':'down'}>{m.change}</span>,m.high,m.low,m.vwap,m.atr,m.symbol==='CL'?'RESEARCH':'ACTIVE',m.signal,'FOMC · 14:00'])}/></Panel></>;
 if(code==='MAC') return <><Title title="Macro Context" sub="Informational regime state · never overrides deterministic strategy logic"/><div className="two"><Panel title="MACRO REGIME" meta="19 AUG 2026"><div className="facts">{[['Growth','SLOWING'],['Inflation','ELEVATED'],['Rates','RESTRICTIVE'],['Liquidity','NEUTRAL'],['Volatility','MODERATE'],['Risk regime','NEUTRAL'],['USD regime','FIRM'],['Commodities','MIXED']].map(x=><span><small>{x[0]}</small><b>{x[1]}</b></span>)}</div></Panel><Panel title="MARKET CONTEXT"><Table heads={['MARKET','LAST','CHANGE','REGIME']} rows={[["US 10Y","4.21%","+3 bp","FIRM"],["DXY","103.84","+0.18%","FIRM"],["VIX","16.42","-0.31","MODERATE"],["WTI","74.18","-0.42%","RANGE"]]}/></Panel></div><Panel title="ECONOMIC CALENDAR"><Table heads={['TIME','COUNTRY','EVENT','IMPACT','PREVIOUS','CONSENSUS','ACTUAL','AITRADER LOCKOUT']} rows={[["14:00 ET","US","FOMC Minutes","HIGH","—","—","—",<Badge tone="amber">13:55–14:10</Badge>],["08:30 ET","US","Initial Jobless Claims","MEDIUM","228K","225K","223K","NONE"],["10:30 ET","US","EIA Crude Inventories","MEDIUM","-1.2M","-0.8M","—","CL ONLY"]]}/></Panel></>;
 if(code==='JRN') return <><Title title="Operational Journal" sub="Complete audit trail for signals, controls, rules and execution"/><Panel title="EVENT LEDGER" meta="FILTER: ALL"><Table heads={['TIME','EVENT','SYMBOL','ACCOUNT','DESCRIPTION','RISK','RESULT','SOURCE']} rows={events.map((e,i)=>[e.time,<Badge tone={e.severity==='warning'?'amber':'neutral'}>{e.type}</Badge>,e.symbol||'—',i===1?'MFFU-01':'—',e.description,i===0?'0.25R':'—',i===3?'+0.74R':'—',i===1?'PROP ENGINE':'AITRADER CORE'])}/></Panel></>;
 if(code==='RES') return <><Title title="Research Registry" sub="Strategy factory lineage and institutional memory"/><Panel title="RESEARCH BRANCHES" meta="INCLUDING CLOSED"><Table heads={['RESEARCH','MARKET','FAMILY','PHASE','SAMPLE','VERDICT','LAST UPDATED']} rows={[["ES VWAP","ES","Mean Reversion","48","Holdout",<Badge tone="amber">VALIDATING</Badge>,"18 Aug"],["CL VWAP","CL","Mean Reversion","49","In sample",<Badge tone="blue">CANDIDATE</Badge>,"17 Aug"],["TG London","GC/NQ","FVG","Closed","Holdout",<Badge>REJECTED</Badge>,"02 Aug"],["ORB Retest","NQ","Breakout","Closed","Cost overlay",<Badge>REJECTED</Badge>,"28 Jul"]]}/></Panel></>;
 if(code==='SYS') return <><Title title="System Operations" sub="AITRADER Core services, connections and heartbeat"/><Panel title="SERVICE REGISTRY" meta="VERSION 0.26.4 · PAPER"><Table heads={['SERVICE','STATUS','MODE','LATENCY','LAST HEARTBEAT','OWNER']} rows={['AITRADER CORE','PORTFOLIO MANAGER','RISK ENGINE','PROP RULE ENGINE','MARKET DATA','PAPER EXECUTION','JOURNAL WRITER','WEBSOCKET'].map((x,i)=>[<b>{x}</b>,<Badge tone="green">HEALTHY</Badge>,i===4?'MOCK':i===5?'PAPER':'ACTIVE',`${[82,14,8,11,126,44,18,32][i]} ms`,'< 1 sec',i<4?'CORE':'INFRA'])}/></Panel></>;
 return <><Title title="Portfolio" sub="Combined allocation, contribution, exposure and portfolio health"/><div className="metric-strip">{[['DRAWDOWN','-1.24%'],['ROLLING SHARPE','1.84'],['EXPECTANCY','0.31R'],['CURRENT HEAT','0.46%'],['MAX HEAT','1.00%'],['CORR. CONC.','62%']].map(m=><div><small>{m[0]}</small><strong>{m[1]}</strong></div>)}</div><div className="two"><Panel title="STRATEGY ALLOCATION"><div className="allocation">{strategies.slice(0,3).map(s=><Meter label={s.name} value={s.allocation}/>) }<Meter label="Cash / unused risk" value={15}/></div></Panel><Panel title="RETURN CORRELATION"><Table heads={['','GC','NQ','ES','CL']} rows={[["GC","1.00","0.08","0.12","0.21"],["NQ","0.08","1.00","0.81","-0.04"],["ES","0.12","0.81","1.00","0.02"],["CL","0.21","-0.04","0.02","1.00"]]}/></Panel></div><Panel title="STRATEGY CONTRIBUTION"><Table heads={['STRATEGY','TODAY','WEEK','MONTH','CONTRIBUTION','RISK CONTRIBUTION']} rows={strategies.slice(0,3).map(s=>[s.name,`${s.dailyR!>=0?'+':''}${s.dailyR}R`,s.market==='NQ'?'+1.12R':'+0.72R',s.market==='GC'?'+4.81R':'+2.34R',`${s.allocation}%`,`${s.allocation+3}%`])}/></Panel></>;
}
const Title=({title,sub}:{title:string;sub:string})=><div className="title"><div><span>AITRADER / OPERATIONS</span><h1>{title}</h1><p>{sub}</p></div><div className="title-actions"><button>EXPORT</button><button>FILTER</button><button className="danger">SAFE MODE</button></div></div>;
export default function Home(){const [active,setActive]=useState('CMD'); const [clock,setClock]=useState('14:37:22'); const [palette,setPalette]=useState(false); const [heartbeat,setHeartbeat]=useState({status:'HEALTHY',latencyMs:328}); useEffect(()=>{const unsubscribeHeartbeat=mockTerminalProvider.events.subscribe('system:heartbeat',event=>setHeartbeat(event.payload)); const disconnect=mockTerminalProvider.connect(); const t=setInterval(()=>setClock(new Date().toLocaleTimeString('en-US',{hour12:false,timeZone:'America/New_York'})),1000); const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setPalette(v=>!v)} if(e.key==='Escape')setPalette(false)};addEventListener('keydown',key);return()=>{unsubscribeHeartbeat();disconnect();clearInterval(t);removeEventListener('keydown',key)}},[]); const name=useMemo(()=>nav.find(n=>n[0]===active)?.[1], [active]); return <main><header className="top"><b className="brand"><i>AI</i>TRADER</b><span>PAPER</span><span>ENGINE <b className="up">● RUNNING</b></span><span>NY <b className="up">OPEN</b></span><span>ACCOUNT <b>MFFU-01</b></span><span>RISK <b className="warn">0.46%</b></span><span>NEWS <b className="warn">SOON</b></span><span><b className={heartbeat.status==='HEALTHY'?'up':'warn'}>●</b> {heartbeat.status} · {heartbeat.latencyMs}ms</span><time>{clock} ET</time><button className="search" onClick={()=>setPalette(true)}>⌕ &nbsp; COMMAND <kbd>CTRL K</kbd></button></header><aside><div className="nav-head"><span>WORKSPACES</span><small>F1–F10</small></div>{nav.map((n,i)=><button onClick={()=>setActive(n[0])} className={active===n[0]?'active':''} key={n[0]}><code>{n[0]}</code><span>{n[1]}</span><kbd>F{i+1}</kbd></button>)}<div className="aside-foot"><small>ACTIVE ENVIRONMENT</small><b>Paper Validation</b><span>core / v0.26.4</span></div></aside><div className="content"><div className="crumb"><span>{active}</span><b>{name}</b><em>19 AUG 2026 · NY SESSION</em></div>{active==='CMD'?<CommandCenter/>:<Workspace code={active}/>}</div>{palette&&<div className="overlay" onClick={()=>setPalette(false)}><div className="palette" onClick={e=>e.stopPropagation()}><header><span>›</span><input autoFocus placeholder="STR NQ · PROP MFFU-01 · RISK · JOURNAL GC"/></header><small>QUICK NAVIGATION · READ-ONLY</small>{nav.map(n=><button onClick={()=>{setActive(n[0]);setPalette(false)}}><code>{n[0]}</code><span>Open {n[1]}</span><kbd>↵</kbd></button>)}</div></div>}</main>}
